name: restaurant_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.4.0
  sqflite: ^2.4.1
  equatable: ^2.0.5
  workmanager:
   git:
     url: https://github.com/fluttercommunity/flutter_workmanager.git
     ref: b783000

  timezone: any
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
   sdk: flutter
  test: ^1.25.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
